<?php
//Глобальные переменные сайта
$site_name = 'Свайно-винтовой фундамент в Екатеринбурге. Строительство свайно-винтового фундамента';
$site_design = 'main_tpl';
$site_webmaster = "";
$site_contact_email1 = "";
$site_mail_relay = "";
$site_domain = $_SERVER["HTTP_HOST"];
$site_mail_protocol = "mail";


//Доступ к базе данных
$db_host = 'localhost';
$db_user = 'root';
$db_pass = '';
$db_name = 'landing-editor';

